import asyncio
import json
from typing import Any

import websockets
from typing_extensions import override

from audio_processor.output_message_type import OutputMessageType
from audio_processor.services.base_service import BaseService


class GatewayService(BaseService):
    def __init__(self, host: str, port: int):
        super().__init__()

        self._host = host
        self._port = port
        self._clients = set()
        self._loop = asyncio.new_event_loop()

    @override
    def stop(self) -> None:
        """Gracefully signals the background async event loop to stop."""
        super().stop()

        if self._loop and self._loop.is_running():
            print("[GatewayService] Signaling async event loop to stop...")
            self._loop.call_soon_threadsafe(self._loop.stop)

    def deliver(self, message_type: OutputMessageType, payload: Any) -> None:
        """
        Thread-safe public entry point. Drops the data off to the
        background async thread immediately to keep the calling thread fast.
        """
        if not self.is_running:
            return

        asyncio.run_coroutine_threadsafe(
            self._broadcast(message_type, payload), self._loop
        )

    @override
    def _run(self) -> None:
        """Executes inside the background thread generated by BaseService."""
        asyncio.set_event_loop(self._loop)

        server = None

        async def start_server():
            serve_websocket = websockets.serve(
                self._client_handler, self._host, self._port
            )
            return await serve_websocket

        try:
            server = self._loop.run_until_complete(start_server())

            print(
                "[GatewayService] Server actively listening on"
                f"ws://{self._host}:{self._port}"
            )

            self._loop.run_forever()
        finally:
            print("[GatewayService] Closing WebSocket server sockets...")

            if server:
                server.close()
                self._loop.run_until_complete(server.wait_closed())

            self._loop.close()

            print("[GatewayService] Async event loop cleanly terminated.")

    async def _client_handler(self, client: websockets.ServerConnection) -> None:
        """Manages the lifetime of a connected websocket client."""
        self._clients.add(client)
        print(f"[GatewayService] Client connected! Total clients: {len(self._clients)}")
        try:
            await client.wait_closed()
        finally:
            self._clients.remove(client)
            print(
                f"[GatewayService] Client disconnected. Total clients: {len(self._clients)}"
            )

    async def _broadcast(self, message_type: OutputMessageType, payload: Any) -> None:
        """Handles JSON packaging and safely transmits data to all clients."""
        if not self._clients:
            return

        try:
            type_string = (
                message_type.value
                if hasattr(message_type, "value")
                else str(message_type)
            )

            message = json.dumps({"type": type_string, "payload": payload})

            await asyncio.gather(
                *(client.send(message) for client in self._clients),
                return_exceptions=True,
            )
        except TypeError as e:
            print(
                f"[GatewayService] Payload formatting failed (Not JSON serializable): {e}"
            )
        except Exception as e:
            print(f"[GatewayService] Unexpected broadcasting error: {e}")
