name: QA - Equipe T3.1

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  testes:
    name: Testes T3.1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip portaudio19-dev

      - name: Instalar dependências Python
        run: |
          pip3 install -r requirements.txt
          pip3 install pytest==9.0.3

      - name: Executar testes
        run: |
          cd audio_processor
          PYTHONPATH=src python3 -m pytest -v
